# Generated by Django 3.2 on 2022-01-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silq', '0002_project_project_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Other_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=500, null=True)),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('issue_code', models.CharField(blank=True, max_length=500, null=True)),
                ('issue_description', models.CharField(blank=True, max_length=500, null=True)),
                ('criticality', models.CharField(blank=True, max_length=500, null=True)),
                ('silq_comments', models.CharField(blank=True, max_length=500, null=True)),
                ('option_1', models.CharField(blank=True, max_length=500, null=True)),
                ('option_2', models.CharField(blank=True, max_length=500, null=True)),
                ('option_3', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_response', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silq.project')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('pom', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('xtra_small', models.CharField(blank=True, max_length=500, null=True)),
                ('small', models.CharField(blank=True, max_length=500, null=True)),
                ('medium', models.CharField(blank=True, max_length=500, null=True)),
                ('large', models.CharField(blank=True, max_length=500, null=True)),
                ('xtra_large', models.CharField(blank=True, max_length=500, null=True)),
                ('xtra_large2', models.CharField(blank=True, max_length=500, null=True)),
                ('xtra_large3', models.CharField(blank=True, max_length=500, null=True)),
                ('tol_plus', models.CharField(blank=True, max_length=500, null=True)),
                ('tol_minus', models.CharField(blank=True, max_length=500, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('issue_code', models.CharField(blank=True, max_length=500, null=True)),
                ('issue_description', models.CharField(blank=True, max_length=500, null=True)),
                ('criticality', models.CharField(blank=True, max_length=500, null=True)),
                ('silq_comment', models.CharField(blank=True, max_length=500, null=True)),
                ('option_1', models.CharField(blank=True, max_length=500, null=True)),
                ('option_2', models.CharField(blank=True, max_length=500, null=True)),
                ('option_3', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_response', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silq.project')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Of_Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('item_style', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('color', models.CharField(blank=True, max_length=500, null=True)),
                ('item_content', models.CharField(blank=True, max_length=500, null=True)),
                ('placement', models.CharField(blank=True, max_length=500, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('supplier', models.CharField(blank=True, max_length=500, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('pricing_estimate', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_code', models.CharField(blank=True, max_length=500, null=True)),
                ('issue_description', models.CharField(blank=True, max_length=500, null=True)),
                ('criticality', models.CharField(blank=True, max_length=500, null=True)),
                ('silq_comment', models.CharField(blank=True, max_length=500, null=True)),
                ('option_1', models.CharField(blank=True, max_length=500, null=True)),
                ('option_2', models.CharField(blank=True, max_length=500, null=True)),
                ('option_3', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_response', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silq.project')),
            ],
        ),
    ]
