# Generated by Django 3.2 on 2022-01-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silq', '0004_auto_20220121_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement_chart',
            old_name='comments',
            new_name='comments2',
        ),
        migrations.RenameField(
            model_name='measurement_chart',
            old_name='criticality',
            new_name='criticality2',
        ),
        migrations.RenameField(
            model_name='measurement_chart',
            old_name='customer_response',
            new_name='customer_response2',
        ),
        migrations.RenameField(
            model_name='measurement_chart',
            old_name='description',
            new_name='description2',
        ),
        migrations.RenameField(
            model_name='measurement_chart',
            old_name='issue_code',
            new_name='issue_code2',
        ),
        migrations.RenameField(
            model_name='measurement_chart',
            old_name='issue_description',
            new_name='issue_description2',
        ),
        migrations.RenameField(
            model_name='measurement_chart',
            old_name='item',
            new_name='item2',
        ),
        migrations.RenameField(
            model_name='measurement_chart',
            old_name='option_1',
            new_name='option_1_2',
        ),
        migrations.RenameField(
            model_name='measurement_chart',
            old_name='option_2',
            new_name='option_2_2',
        ),
        migrations.RenameField(
            model_name='measurement_chart',
            old_name='option_3',
            new_name='option_3_2',
        ),
        migrations.RenameField(
            model_name='measurement_chart',
            old_name='silq_comment',
            new_name='silq_comment2',
        ),
        migrations.RenameField(
            model_name='other_issue',
            old_name='criticality',
            new_name='criticality3',
        ),
        migrations.RenameField(
            model_name='other_issue',
            old_name='customer_response',
            new_name='customer_response_3',
        ),
        migrations.RenameField(
            model_name='other_issue',
            old_name='issue_code',
            new_name='issue_code3',
        ),
        migrations.RenameField(
            model_name='other_issue',
            old_name='issue_description',
            new_name='issue_description3',
        ),
        migrations.RenameField(
            model_name='other_issue',
            old_name='item',
            new_name='item3',
        ),
        migrations.RenameField(
            model_name='other_issue',
            old_name='option_1',
            new_name='option_1_3',
        ),
        migrations.RenameField(
            model_name='other_issue',
            old_name='option_2',
            new_name='option_2_3',
        ),
        migrations.RenameField(
            model_name='other_issue',
            old_name='option_3',
            new_name='option_3_3',
        ),
        migrations.RenameField(
            model_name='other_issue',
            old_name='silq_comments',
            new_name='silq_comments3',
        ),
    ]
