# Generated by Django 3.2 on 2022-01-21 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silq', '0005_auto_20220121_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_of_materials',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silq.project'),
        ),
        migrations.AlterField(
            model_name='measurement_chart',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silq.project'),
        ),
        migrations.AlterField(
            model_name='other_issue',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silq.project'),
        ),
    ]
