# Generated by Django 3.2 on 2022-01-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silq', '0006_auto_20220122_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='style',
            field=models.CharField(blank=True, choices=[('Polo', 'Polo'), ('Hoodie', 'Hoodie'), ('Shorts', 'Shorts'), ('Pants', 'Pants'), ('Shirts', 'Shirts'), ('T-Shirts', 'T-Shirts'), ('Trouser', 'Trouser'), ('Bag', 'Bag'), ('Joggers', 'Joggers'), ('Sweat-Shirt', 'Sweat-Shirt'), ('Boxers', 'Boxers'), ('UnderWear', 'UnderWear')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='style_hash',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
