# Generated by Django 3.2 on 2022-01-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silq', '0010_alter_project_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Po_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(blank=True, choices=[('Sampling', 'Sampling'), ('Production Management', 'Production Management'), ('The Works', 'The Works'), ('Tech Pack Bundle', 'Tech Pack Bundle')], max_length=500, null=True)),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_po_number', models.CharField(blank=True, max_length=200, null=True)),
                ('total_po_value', models.CharField(blank=True, max_length=200, null=True)),
                ('project_recieved_date', models.CharField(blank=True, max_length=200, null=True)),
                ('project_estimated_delivery', models.CharField(blank=True, max_length=200, null=True)),
                ('project_actual_delivery_date', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_name', models.CharField(blank=True, max_length=200, null=True)),
                ('style_name', models.CharField(blank=True, max_length=200, null=True)),
                ('style_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_style_item_description', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('sample', models.CharField(blank=True, choices=[('Fit Sample', 'Fit Sample'), ('Lab Dip', 'Lab Dip'), ('Pre-Production', 'Pre-Production'), ('Swatch', 'Swatch'), ('Print Strike-O', 'Print Strike-O'), ('Sewing Trim', 'Sewing Trim'), ('Packaging', 'Packaging'), ('Top Sample', 'Top Sample'), ('Size Set', 'Size Set'), ('Fit Sample', 'Fit Sample'), ('Photo Sample', 'Photo Sample')], max_length=200, null=True)),
                ('sample_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('sample_quantity', models.CharField(blank=True, max_length=200, null=True)),
                ('assigned_inspector', models.CharField(blank=True, max_length=200, null=True)),
                ('status_from_vendor', models.CharField(blank=True, choices=[('RECEIVED', 'RECEIVED'), ('PENDING', 'PENDING'), ('NOT REQUIRED', 'NOT REQUIRED')], max_length=200, null=True)),
                ('date_recieved_from_vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('silq_approval_status', models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], max_length=200, null=True)),
                ('silq_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('date_sent_to_customer', models.CharField(blank=True, max_length=200, null=True)),
                ('courier_number', models.CharField(blank=True, max_length=200, null=True)),
                ('approval_status_from_customer', models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('NOT REQUIRED', 'NOT REQUIRED'), ('LOCAL APPROVAL', 'LOCAL APPROVAL')], max_length=200, null=True)),
                ('date_approved_by_customer', models.CharField(blank=True, max_length=200, null=True)),
                ('comment_from_customer', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
