# Generated by Django 3.2 on 2022-01-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silq', '0012_rename_project_estimated_delivery_po_summary_project_estimated_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_summary',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silq.project'),
        ),
        migrations.AddField(
            model_name='style_data',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silq.project'),
        ),
    ]
