# Generated by Django 3.2 on 2022-01-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_user_type'),
        ('silq', '0013_auto_20220123_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po_summary',
            name='project',
        ),
        migrations.RemoveField(
            model_name='style_data',
            name='project',
        ),
        migrations.AddField(
            model_name='po_summary',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='style_data',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
