# Generated by Django 3.2 on 2022-01-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silq', '0014_auto_20220123_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po_summary',
            name='project_actual_delivery_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po_summary',
            name='project_estimated_delivery_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po_summary',
            name='project_recieved_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
