# Generated by Django 3.2 on 2022-01-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silq', '0015_auto_20220123_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style_data',
            name='date_approved_by_customer',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='style_data',
            name='date_recieved_from_vendor',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='style_data',
            name='date_sent_to_customer',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
